### ISSUE TITLE
无法执行python manager.py createsuperuser

### ISSUE THREAD

**Issue by PJho555** [small-flying-pigs/devops-api#3]
# 问题描述:
无法创建超级用户, 提示user_id不能为null, 而user_id又是approved_users的外键, 无法配置auto_increment
# 需求
怎么登录页面?

**Comment by zijiwork** [comment]
这个问题已经在v2.1分支修复

**Comment by PJho555** [comment]
> 这个问题已经在v2.1分支修复

可以了, 谢谢
